In [1]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("C:/Users/Acer/Desktop/Kaggle/movie prediction 2/movies.csv")

In [3]:
df.head(1)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity  ... runtime                                   spoken_languages  \
0  150.437577  ...   162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   

     status                      tagline   title vote_average vote_count  \
0  Released  Enter the World of Pandora.  Avatar          7.2      11800   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   

                                                crew       director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...  James Cameron  

[1 rows x 24 columns]

In [4]:
df.shape

(4803, 24)

In [5]:
df.describe()

index        budget             id   popularity       revenue  \
count  4803.000000  4.803000e+03    4803.000000  4803.000000  4.803000e+03   
mean   2401.000000  2.904504e+07   57165.484281    21.492301  8.226064e+07   
std    1386.651002  4.072239e+07   88694.614033    31.816650  1.628571e+08   
min       0.000000  0.000000e+00       5.000000     0.000000  0.000000e+00   
25%    1200.500000  7.900000e+05    9014.500000     4.668070  0.000000e+00   
50%    2401.000000  1.500000e+07   14629.000000    12.921594  1.917000e+07   
75%    3601.500000  4.000000e+07   58610.500000    28.313505  9.291719e+07   
max    4802.000000  3.800000e+08  459488.000000   875.581305  2.787965e+09   

           runtime  vote_average    vote_count  
count  4801.000000   4803.000000   4803.000000  
mean    106.875859      6.092172    690.217989  
std      22.611935      1.194612   1234.585891  
min       0.000000      0.000000      0.000000  
25%      94.000000      5.600000     54.000000  
50%     103.000000      6.200000    235.000000  
75%     118.000000      6.800000    737.000000  
max     338.000000     10.000000  13752.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [7]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [8]:
cols1 = ['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director']
cols2 = ['budget', 'genres','keywords', 'original_language','popularity', 'production_companies','production_countries',
        'revenue','tagline', 'vote_average','vote_count', 'cast', 'director']

In [9]:
print(cols2 in cols1)

False


##### I am using cols2 as the columns for my recommendation system

In [10]:
for col in cols2:
    df[col] = df[col].fillna('')        ### fill the empty strings

### Combining the features

In [11]:
len(cols2)

13

In [12]:
comb_feat = ''
for i in cols2:
    comb_feat += df[i].astype(str) + '_'

In [13]:
comb_feat

0       237000000_Action Adventure Fantasy Science Fic...
1       300000000_Adventure Fantasy Action_ocean drug ...
2       245000000_Action Adventure Crime_spy based on ...
3       250000000_Action Crime Drama Thriller_dc comic...
4       260000000_Action Adventure Science Fiction_bas...
                              ...                        
4798    220000_Action Crime Thriller_united states\u20...
4799    9000_Comedy Romance__en_0.642552_[]_[]_0_A new...
4800    0_Comedy Drama Romance TV Movie_date love at f...
4801    0___en_0.857008_[]_[{"iso_3166_1": "US", "name...
4802    0_Documentary_obsession camcorder crush dream ...
Name: budget, Length: 4803, dtype: object

In [14]:
vec = TfidfVectorizer()

In [15]:
vec_feat = vec.fit_transform(comb_feat)      ## vectorized features

In [16]:
print(vec_feat)

  (0, 5082)	0.2062074568658828
  (0, 20797)	0.08159483402936779
  (0, 29907)	0.09942818575108148
  (0, 44569)	0.07943147990624706
  (0, 30310)	0.2062074568658828
  (0, 25449)	0.16414555274187256
  (0, 31276)	0.12274496546669864
  (0, 45836)	0.25195130847993863
  (0, 49773)	0.09942818575108148
  (0, 25704)	0.18041731842987604
  (0, 45667)	0.2062074568658828
  (0, 8758)	0.2062074568658828
  (0, 39691)	0.1454706363491117
  (0, 34319)	0.13708617570750545
  (0, 30518)	0.12589739960540985
  (0, 40997)	0.12448466461331323
  (0, 34068)	0.10102511747209644
  (0, 5917)	0.14263544852547655
  (0, 48491)	0.09471740191095815
  (0, 24890)	0.09352853037385267
  (0, 30982)	0.08212370936660161
  (0, 26295)	0.0817113364802164
  (0, 6654)	0.09554480722681319
  (0, 28609)	0.11684531008946984
  (0, 29191)	0.10930391889169858
  :	:
  (4802, 30587)	0.05823228659190877
  (4802, 28448)	0.1471022236740353
  (4802, 23880)	0.14567393159812997
  (4802, 29247)	0.14521420792996026
  (4802, 26268)	0.18389951213578867


In [17]:
similarity = cosine_similarity(vec_feat)

In [18]:
print(similarity)

[[1.         0.0632116  0.05393694 ... 0.03085113 0.01913145 0.03216303]
 [0.0632116  1.         0.04234815 ... 0.02826255 0.01419143 0.02157971]
 [0.05393694 0.04234815 1.         ... 0.02343177 0.01760463 0.02221665]
 ...
 [0.03085113 0.02826255 0.02343177 ... 1.         0.01219938 0.01915288]
 [0.01913145 0.01419143 0.01760463 ... 0.01219938 1.         0.01271814]
 [0.03216303 0.02157971 0.02221665 ... 0.01915288 0.01271814 1.        ]]


## Getting Input from the User

In [19]:
movie_name = input('For the movie for which you want to find similar movies, enter its name:')

For the movie for which you want to find similar movies, enter its name: Spider man


#### List of all movie names

In [20]:
movies_list  = df['title'].tolist()

In [21]:
movies_list

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',

### Finding close match

In [28]:
find_close_match = difflib.get_close_matches(movie_name, movies_list)
print(find_close_match)          ### these 3 movies are close to Iron man

['Spider-Man', 'Superman', 'Spider']


In [29]:
mov_name = 'Man of Steel'
find_close_match = difflib.get_close_matches(mov_name, movies_list)
print(find_close_match)          ### not getting good results here

['Man of Steel', 'Man of the Year', 'Man of the House']


#### Getting a similarity score

In [32]:
close_match = find_close_match[0]
print(close_match)

Shrek the Third


In [33]:
# finding the index of the movie with title

index_of_the_movie = df[df.title == close_match]['index'].values[0]
print(index_of_the_movie)

106


In [27]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.033190349663090375), (1, 0.030451667239064492), (2, 0.02988125451426271), (3, 0.022771077378393817), (4, 0.02417685869396401), (5, 0.02074047780209916), (6, 0.06769617251356501), (7, 0.025229122392170837), (8, 0.021716480943711924), (9, 0.03151564909376463), (10, 0.021751760458761725), (11, 0.047801895622476845), (12, 0.023616817418379753), (13, 0.030413180206681205), (14, 0.036886237687372744), (15, 0.0332181426342521), (16, 0.015040445777321056), (17, 0.021245539376528545), (18, 0.030114360705122453), (19, 0.03125549565936302), (20, 0.03021024750596169), (21, 0.027108751238158316), (22, 0.024216602554355766), (23, 0.023743264977980214), (24, 0.028754720374356498), (25, 0.01886857568525643), (26, 0.021548459777003537), (27, 0.03593191033758665), (28, 0.033912085265102254), (29, 0.029716519133700114), (30, 0.034326857027087355), (31, 0.025576132051708535), (32, 0.025509900486615965), (33, 0.036949028997057556), (34, 0.06804910993093935), (35, 0.08673569192849778), (36, 0.0292316

### The end